// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skycubed/nifi-go/pkg/nifi/models"
)

// CreateParameterProviderReader is a Reader for the CreateParameterProvider structure.
type CreateParameterProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateParameterProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateParameterProviderCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateParameterProviderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateParameterProviderUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateParameterProviderForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateParameterProviderConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateParameterProviderCreated creates a CreateParameterProviderCreated with default headers values
func NewCreateParameterProviderCreated() *CreateParameterProviderCreated {
	return &CreateParameterProviderCreated{}
}

/*
CreateParameterProviderCreated describes a response with status code 201, with default header values.

successful operation
*/
type CreateParameterProviderCreated struct {
	Payload *models.ParameterProviderEntity
}

// IsSuccess returns true when this create parameter provider created response has a 2xx status code
func (o *CreateParameterProviderCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create parameter provider created response has a 3xx status code
func (o *CreateParameterProviderCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create parameter provider created response has a 4xx status code
func (o *CreateParameterProviderCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create parameter provider created response has a 5xx status code
func (o *CreateParameterProviderCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create parameter provider created response a status code equal to that given
func (o *CreateParameterProviderCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateParameterProviderCreated) Error() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderCreated  %+v", 201, o.Payload)
}

func (o *CreateParameterProviderCreated) String() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderCreated  %+v", 201, o.Payload)
}

func (o *CreateParameterProviderCreated) GetPayload() *models.ParameterProviderEntity {
	return o.Payload
}

func (o *CreateParameterProviderCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ParameterProviderEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateParameterProviderBadRequest creates a CreateParameterProviderBadRequest with default headers values
func NewCreateParameterProviderBadRequest() *CreateParameterProviderBadRequest {
	return &CreateParameterProviderBadRequest{}
}

/*
CreateParameterProviderBadRequest describes a response with status code 400, with default header values.

NiFi was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type CreateParameterProviderBadRequest struct {
}

// IsSuccess returns true when this create parameter provider bad request response has a 2xx status code
func (o *CreateParameterProviderBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create parameter provider bad request response has a 3xx status code
func (o *CreateParameterProviderBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create parameter provider bad request response has a 4xx status code
func (o *CreateParameterProviderBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create parameter provider bad request response has a 5xx status code
func (o *CreateParameterProviderBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create parameter provider bad request response a status code equal to that given
func (o *CreateParameterProviderBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateParameterProviderBadRequest) Error() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderBadRequest ", 400)
}

func (o *CreateParameterProviderBadRequest) String() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderBadRequest ", 400)
}

func (o *CreateParameterProviderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateParameterProviderUnauthorized creates a CreateParameterProviderUnauthorized with default headers values
func NewCreateParameterProviderUnauthorized() *CreateParameterProviderUnauthorized {
	return &CreateParameterProviderUnauthorized{}
}

/*
CreateParameterProviderUnauthorized describes a response with status code 401, with default header values.

Client could not be authenticated.
*/
type CreateParameterProviderUnauthorized struct {
}

// IsSuccess returns true when this create parameter provider unauthorized response has a 2xx status code
func (o *CreateParameterProviderUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create parameter provider unauthorized response has a 3xx status code
func (o *CreateParameterProviderUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create parameter provider unauthorized response has a 4xx status code
func (o *CreateParameterProviderUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create parameter provider unauthorized response has a 5xx status code
func (o *CreateParameterProviderUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create parameter provider unauthorized response a status code equal to that given
func (o *CreateParameterProviderUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateParameterProviderUnauthorized) Error() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderUnauthorized ", 401)
}

func (o *CreateParameterProviderUnauthorized) String() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderUnauthorized ", 401)
}

func (o *CreateParameterProviderUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateParameterProviderForbidden creates a CreateParameterProviderForbidden with default headers values
func NewCreateParameterProviderForbidden() *CreateParameterProviderForbidden {
	return &CreateParameterProviderForbidden{}
}

/*
CreateParameterProviderForbidden describes a response with status code 403, with default header values.

Client is not authorized to make this request.
*/
type CreateParameterProviderForbidden struct {
}

// IsSuccess returns true when this create parameter provider forbidden response has a 2xx status code
func (o *CreateParameterProviderForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create parameter provider forbidden response has a 3xx status code
func (o *CreateParameterProviderForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create parameter provider forbidden response has a 4xx status code
func (o *CreateParameterProviderForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create parameter provider forbidden response has a 5xx status code
func (o *CreateParameterProviderForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create parameter provider forbidden response a status code equal to that given
func (o *CreateParameterProviderForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateParameterProviderForbidden) Error() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderForbidden ", 403)
}

func (o *CreateParameterProviderForbidden) String() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderForbidden ", 403)
}

func (o *CreateParameterProviderForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateParameterProviderConflict creates a CreateParameterProviderConflict with default headers values
func NewCreateParameterProviderConflict() *CreateParameterProviderConflict {
	return &CreateParameterProviderConflict{}
}

/*
CreateParameterProviderConflict describes a response with status code 409, with default header values.

The request was valid but NiFi was not in the appropriate state to process it. Retrying the same request later may be successful.
*/
type CreateParameterProviderConflict struct {
}

// IsSuccess returns true when this create parameter provider conflict response has a 2xx status code
func (o *CreateParameterProviderConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create parameter provider conflict response has a 3xx status code
func (o *CreateParameterProviderConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create parameter provider conflict response has a 4xx status code
func (o *CreateParameterProviderConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create parameter provider conflict response has a 5xx status code
func (o *CreateParameterProviderConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create parameter provider conflict response a status code equal to that given
func (o *CreateParameterProviderConflict) IsCode(code int) bool {
	return code == 409
}

func (o *CreateParameterProviderConflict) Error() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderConflict ", 409)
}

func (o *CreateParameterProviderConflict) String() string {
	return fmt.Sprintf("[POST /controller/parameter-providers][%d] createParameterProviderConflict ", 409)
}

func (o *CreateParameterProviderConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
