// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skycubed/nifi-go/pkg/nifi/models"
)

// CreateBulletinReader is a Reader for the CreateBulletin structure.
type CreateBulletinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateBulletinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateBulletinOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateBulletinBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateBulletinUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateBulletinForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateBulletinConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateBulletinOK creates a CreateBulletinOK with default headers values
func NewCreateBulletinOK() *CreateBulletinOK {
	return &CreateBulletinOK{}
}

/* CreateBulletinOK describes a response with status code 200, with default header values.

successful operation
*/
type CreateBulletinOK struct {
	Payload *models.BulletinEntity
}

func (o *CreateBulletinOK) Error() string {
	return fmt.Sprintf("[POST /controller/bulletin][%d] createBulletinOK  %+v", 200, o.Payload)
}
func (o *CreateBulletinOK) GetPayload() *models.BulletinEntity {
	return o.Payload
}

func (o *CreateBulletinOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BulletinEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBulletinBadRequest creates a CreateBulletinBadRequest with default headers values
func NewCreateBulletinBadRequest() *CreateBulletinBadRequest {
	return &CreateBulletinBadRequest{}
}

/* CreateBulletinBadRequest describes a response with status code 400, with default header values.

NiFi was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type CreateBulletinBadRequest struct {
}

func (o *CreateBulletinBadRequest) Error() string {
	return fmt.Sprintf("[POST /controller/bulletin][%d] createBulletinBadRequest ", 400)
}

func (o *CreateBulletinBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBulletinUnauthorized creates a CreateBulletinUnauthorized with default headers values
func NewCreateBulletinUnauthorized() *CreateBulletinUnauthorized {
	return &CreateBulletinUnauthorized{}
}

/* CreateBulletinUnauthorized describes a response with status code 401, with default header values.

Client could not be authenticated.
*/
type CreateBulletinUnauthorized struct {
}

func (o *CreateBulletinUnauthorized) Error() string {
	return fmt.Sprintf("[POST /controller/bulletin][%d] createBulletinUnauthorized ", 401)
}

func (o *CreateBulletinUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBulletinForbidden creates a CreateBulletinForbidden with default headers values
func NewCreateBulletinForbidden() *CreateBulletinForbidden {
	return &CreateBulletinForbidden{}
}

/* CreateBulletinForbidden describes a response with status code 403, with default header values.

Client is not authorized to make this request.
*/
type CreateBulletinForbidden struct {
}

func (o *CreateBulletinForbidden) Error() string {
	return fmt.Sprintf("[POST /controller/bulletin][%d] createBulletinForbidden ", 403)
}

func (o *CreateBulletinForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBulletinConflict creates a CreateBulletinConflict with default headers values
func NewCreateBulletinConflict() *CreateBulletinConflict {
	return &CreateBulletinConflict{}
}

/* CreateBulletinConflict describes a response with status code 409, with default header values.

The request was valid but NiFi was not in the appropriate state to process it. Retrying the same request later may be successful.
*/
type CreateBulletinConflict struct {
}

func (o *CreateBulletinConflict) Error() string {
	return fmt.Sprintf("[POST /controller/bulletin][%d] createBulletinConflict ", 409)
}

func (o *CreateBulletinConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
