// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skycubed/nifi-go/pkg/nifi/models"
)

// DeleteHistoryReader is a Reader for the DeleteHistory structure.
type DeleteHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteHistoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteHistoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteHistoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDeleteHistoryConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteHistoryOK creates a DeleteHistoryOK with default headers values
func NewDeleteHistoryOK() *DeleteHistoryOK {
	return &DeleteHistoryOK{}
}

/* DeleteHistoryOK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteHistoryOK struct {
	Payload *models.HistoryEntity
}

func (o *DeleteHistoryOK) Error() string {
	return fmt.Sprintf("[DELETE /controller/history][%d] deleteHistoryOK  %+v", 200, o.Payload)
}
func (o *DeleteHistoryOK) GetPayload() *models.HistoryEntity {
	return o.Payload
}

func (o *DeleteHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HistoryEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteHistoryBadRequest creates a DeleteHistoryBadRequest with default headers values
func NewDeleteHistoryBadRequest() *DeleteHistoryBadRequest {
	return &DeleteHistoryBadRequest{}
}

/* DeleteHistoryBadRequest describes a response with status code 400, with default header values.

NiFi was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type DeleteHistoryBadRequest struct {
}

func (o *DeleteHistoryBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /controller/history][%d] deleteHistoryBadRequest ", 400)
}

func (o *DeleteHistoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHistoryUnauthorized creates a DeleteHistoryUnauthorized with default headers values
func NewDeleteHistoryUnauthorized() *DeleteHistoryUnauthorized {
	return &DeleteHistoryUnauthorized{}
}

/* DeleteHistoryUnauthorized describes a response with status code 401, with default header values.

Client could not be authenticated.
*/
type DeleteHistoryUnauthorized struct {
}

func (o *DeleteHistoryUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /controller/history][%d] deleteHistoryUnauthorized ", 401)
}

func (o *DeleteHistoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHistoryForbidden creates a DeleteHistoryForbidden with default headers values
func NewDeleteHistoryForbidden() *DeleteHistoryForbidden {
	return &DeleteHistoryForbidden{}
}

/* DeleteHistoryForbidden describes a response with status code 403, with default header values.

Client is not authorized to make this request.
*/
type DeleteHistoryForbidden struct {
}

func (o *DeleteHistoryForbidden) Error() string {
	return fmt.Sprintf("[DELETE /controller/history][%d] deleteHistoryForbidden ", 403)
}

func (o *DeleteHistoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHistoryConflict creates a DeleteHistoryConflict with default headers values
func NewDeleteHistoryConflict() *DeleteHistoryConflict {
	return &DeleteHistoryConflict{}
}

/* DeleteHistoryConflict describes a response with status code 409, with default header values.

The request was valid but NiFi was not in the appropriate state to process it. Retrying the same request later may be successful.
*/
type DeleteHistoryConflict struct {
}

func (o *DeleteHistoryConflict) Error() string {
	return fmt.Sprintf("[DELETE /controller/history][%d] deleteHistoryConflict ", 409)
}

func (o *DeleteHistoryConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
