version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, go]
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
    labels: [dependencies, tooling]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github-actions]
