FROM golang:1.22.5-alpine

RUN mkdir /swagger

COPY swagger /swagger/

RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

RUN mkdir -p /go/src/github.com/skycubed/nifi-go/pkg/nifi /go/src/github.com/skycubed/nifi-go/pkg/registry

WORKDIR /go/src/github.com/skycubed/nifi-go/pkg

RUN oapi-codegen -package=nifi -generate "types,client,spec" /swagger/nifi/swagger.json > nifi/nifi.go
RUN oapi-codegen -package=registry -generate "types,client,spec" /swagger/registry/swagger.json > registry/registry.go
