// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectionStatisticsSnapshotDTO connection statistics snapshot d t o
//
// swagger:model ConnectionStatisticsSnapshotDTO
type ConnectionStatisticsSnapshotDTO struct {

	// The id of the connection.
	ID string `json:"id,omitempty"`

	// The predicted total number of bytes in the queue at the next configured interval.
	PredictedBytesAtNextInterval int64 `json:"predictedBytesAtNextInterval,omitempty"`

	// The predicted number of queued objects at the next configured interval.
	PredictedCountAtNextInterval int32 `json:"predictedCountAtNextInterval,omitempty"`

	// The predicted number of milliseconds before the connection will have backpressure applied, based on the total number of bytes in the queue.
	PredictedMillisUntilBytesBackpressure int64 `json:"predictedMillisUntilBytesBackpressure,omitempty"`

	// The predicted number of milliseconds before the connection will have backpressure applied, based on the queued count.
	PredictedMillisUntilCountBackpressure int64 `json:"predictedMillisUntilCountBackpressure,omitempty"`

	// The predicted percentage of bytes in the queue against current threshold at the next configured interval.
	PredictedPercentBytes int32 `json:"predictedPercentBytes,omitempty"`

	// The predicted percentage of queued objects at the next configured interval.
	PredictedPercentCount int32 `json:"predictedPercentCount,omitempty"`

	// The prediction interval in seconds
	PredictionIntervalMillis int64 `json:"predictionIntervalMillis,omitempty"`
}

// Validate validates this connection statistics snapshot d t o
func (m *ConnectionStatisticsSnapshotDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connection statistics snapshot d t o based on context it is used
func (m *ConnectionStatisticsSnapshotDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnectionStatisticsSnapshotDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectionStatisticsSnapshotDTO) UnmarshalBinary(b []byte) error {
	var res ConnectionStatisticsSnapshotDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
