// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ControllerServiceReferencingComponentsEntity controller service referencing components entity
//
// swagger:model ControllerServiceReferencingComponentsEntity
type ControllerServiceReferencingComponentsEntity struct {

	// controller service referencing components
	// Unique: true
	ControllerServiceReferencingComponents []*ControllerServiceReferencingComponentEntity `json:"controllerServiceReferencingComponents"`
}

// Validate validates this controller service referencing components entity
func (m *ControllerServiceReferencingComponentsEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateControllerServiceReferencingComponents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ControllerServiceReferencingComponentsEntity) validateControllerServiceReferencingComponents(formats strfmt.Registry) error {
	if swag.IsZero(m.ControllerServiceReferencingComponents) { // not required
		return nil
	}

	if err := validate.UniqueItems("controllerServiceReferencingComponents", "body", m.ControllerServiceReferencingComponents); err != nil {
		return err
	}

	for i := 0; i < len(m.ControllerServiceReferencingComponents); i++ {
		if swag.IsZero(m.ControllerServiceReferencingComponents[i]) { // not required
			continue
		}

		if m.ControllerServiceReferencingComponents[i] != nil {
			if err := m.ControllerServiceReferencingComponents[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("controllerServiceReferencingComponents" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("controllerServiceReferencingComponents" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this controller service referencing components entity based on the context it is used
func (m *ControllerServiceReferencingComponentsEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateControllerServiceReferencingComponents(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ControllerServiceReferencingComponentsEntity) contextValidateControllerServiceReferencingComponents(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ControllerServiceReferencingComponents); i++ {

		if m.ControllerServiceReferencingComponents[i] != nil {
			if err := m.ControllerServiceReferencingComponents[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("controllerServiceReferencingComponents" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("controllerServiceReferencingComponents" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ControllerServiceReferencingComponentsEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerServiceReferencingComponentsEntity) UnmarshalBinary(b []byte) error {
	var res ControllerServiceReferencingComponentsEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
