// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ParameterProviderConfigurationDTO parameter provider configuration d t o
//
// swagger:model ParameterProviderConfigurationDTO
type ParameterProviderConfigurationDTO struct {

	// The Parameter Group name that maps to the Parameter Context
	ParameterGroupName string `json:"parameterGroupName,omitempty"`

	// The ID of the Parameter Provider
	ParameterProviderID string `json:"parameterProviderId,omitempty"`

	// The name of the Parameter Provider
	ParameterProviderName string `json:"parameterProviderName,omitempty"`

	// True if the Parameter Context should receive the parameters from the mapped Parameter Group
	Synchronized bool `json:"synchronized,omitempty"`
}

// Validate validates this parameter provider configuration d t o
func (m *ParameterProviderConfigurationDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this parameter provider configuration d t o based on context it is used
func (m *ParameterProviderConfigurationDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParameterProviderConfigurationDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParameterProviderConfigurationDTO) UnmarshalBinary(b []byte) error {
	var res ParameterProviderConfigurationDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
