// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProvenanceSearchValueDTO provenance search value d t o
//
// swagger:model ProvenanceSearchValueDTO
type ProvenanceSearchValueDTO struct {

	// Query for all except for search value.
	Inverse bool `json:"inverse,omitempty"`

	// The search value.
	Value string `json:"value,omitempty"`
}

// Validate validates this provenance search value d t o
func (m *ProvenanceSearchValueDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this provenance search value d t o based on context it is used
func (m *ProvenanceSearchValueDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProvenanceSearchValueDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProvenanceSearchValueDTO) UnmarshalBinary(b []byte) error {
	var res ProvenanceSearchValueDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
