// Code generated by go-swagger; DO NOT EDIT.

package process_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDropAllFlowfilesRequestParams creates a new GetDropAllFlowfilesRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDropAllFlowfilesRequestParams() *GetDropAllFlowfilesRequestParams {
	return &GetDropAllFlowfilesRequestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDropAllFlowfilesRequestParamsWithTimeout creates a new GetDropAllFlowfilesRequestParams object
// with the ability to set a timeout on a request.
func NewGetDropAllFlowfilesRequestParamsWithTimeout(timeout time.Duration) *GetDropAllFlowfilesRequestParams {
	return &GetDropAllFlowfilesRequestParams{
		timeout: timeout,
	}
}

// NewGetDropAllFlowfilesRequestParamsWithContext creates a new GetDropAllFlowfilesRequestParams object
// with the ability to set a context for a request.
func NewGetDropAllFlowfilesRequestParamsWithContext(ctx context.Context) *GetDropAllFlowfilesRequestParams {
	return &GetDropAllFlowfilesRequestParams{
		Context: ctx,
	}
}

// NewGetDropAllFlowfilesRequestParamsWithHTTPClient creates a new GetDropAllFlowfilesRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDropAllFlowfilesRequestParamsWithHTTPClient(client *http.Client) *GetDropAllFlowfilesRequestParams {
	return &GetDropAllFlowfilesRequestParams{
		HTTPClient: client,
	}
}

/* GetDropAllFlowfilesRequestParams contains all the parameters to send to the API endpoint
   for the get drop all flowfiles request operation.

   Typically these are written to a http.Request.
*/
type GetDropAllFlowfilesRequestParams struct {

	/* DropRequestID.

	   The drop request id.
	*/
	DropRequestID string

	/* ID.

	   The process group id.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get drop all flowfiles request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDropAllFlowfilesRequestParams) WithDefaults() *GetDropAllFlowfilesRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get drop all flowfiles request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDropAllFlowfilesRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) WithTimeout(timeout time.Duration) *GetDropAllFlowfilesRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) WithContext(ctx context.Context) *GetDropAllFlowfilesRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) WithHTTPClient(client *http.Client) *GetDropAllFlowfilesRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDropRequestID adds the dropRequestID to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) WithDropRequestID(dropRequestID string) *GetDropAllFlowfilesRequestParams {
	o.SetDropRequestID(dropRequestID)
	return o
}

// SetDropRequestID adds the dropRequestId to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) SetDropRequestID(dropRequestID string) {
	o.DropRequestID = dropRequestID
}

// WithID adds the id to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) WithID(id string) *GetDropAllFlowfilesRequestParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get drop all flowfiles request params
func (o *GetDropAllFlowfilesRequestParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDropAllFlowfilesRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param drop-request-id
	if err := r.SetPathParam("drop-request-id", o.DropRequestID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
