// Code generated by go-swagger; DO NOT EDIT.

package process_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skycubed/nifi-go/pkg/nifi/models"
)

// SubmitUpdateVariableRegistryRequestReader is a Reader for the SubmitUpdateVariableRegistryRequest structure.
type SubmitUpdateVariableRegistryRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubmitUpdateVariableRegistryRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSubmitUpdateVariableRegistryRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSubmitUpdateVariableRegistryRequestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSubmitUpdateVariableRegistryRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSubmitUpdateVariableRegistryRequestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSubmitUpdateVariableRegistryRequestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewSubmitUpdateVariableRegistryRequestConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSubmitUpdateVariableRegistryRequestOK creates a SubmitUpdateVariableRegistryRequestOK with default headers values
func NewSubmitUpdateVariableRegistryRequestOK() *SubmitUpdateVariableRegistryRequestOK {
	return &SubmitUpdateVariableRegistryRequestOK{}
}

/*
SubmitUpdateVariableRegistryRequestOK describes a response with status code 200, with default header values.

successful operation
*/
type SubmitUpdateVariableRegistryRequestOK struct {
	Payload *models.VariableRegistryUpdateRequestEntity
}

// IsSuccess returns true when this submit update variable registry request o k response has a 2xx status code
func (o *SubmitUpdateVariableRegistryRequestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this submit update variable registry request o k response has a 3xx status code
func (o *SubmitUpdateVariableRegistryRequestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit update variable registry request o k response has a 4xx status code
func (o *SubmitUpdateVariableRegistryRequestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this submit update variable registry request o k response has a 5xx status code
func (o *SubmitUpdateVariableRegistryRequestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this submit update variable registry request o k response a status code equal to that given
func (o *SubmitUpdateVariableRegistryRequestOK) IsCode(code int) bool {
	return code == 200
}

func (o *SubmitUpdateVariableRegistryRequestOK) Error() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestOK  %+v", 200, o.Payload)
}

func (o *SubmitUpdateVariableRegistryRequestOK) String() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestOK  %+v", 200, o.Payload)
}

func (o *SubmitUpdateVariableRegistryRequestOK) GetPayload() *models.VariableRegistryUpdateRequestEntity {
	return o.Payload
}

func (o *SubmitUpdateVariableRegistryRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VariableRegistryUpdateRequestEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSubmitUpdateVariableRegistryRequestBadRequest creates a SubmitUpdateVariableRegistryRequestBadRequest with default headers values
func NewSubmitUpdateVariableRegistryRequestBadRequest() *SubmitUpdateVariableRegistryRequestBadRequest {
	return &SubmitUpdateVariableRegistryRequestBadRequest{}
}

/*
SubmitUpdateVariableRegistryRequestBadRequest describes a response with status code 400, with default header values.

NiFi was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type SubmitUpdateVariableRegistryRequestBadRequest struct {
}

// IsSuccess returns true when this submit update variable registry request bad request response has a 2xx status code
func (o *SubmitUpdateVariableRegistryRequestBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this submit update variable registry request bad request response has a 3xx status code
func (o *SubmitUpdateVariableRegistryRequestBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit update variable registry request bad request response has a 4xx status code
func (o *SubmitUpdateVariableRegistryRequestBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this submit update variable registry request bad request response has a 5xx status code
func (o *SubmitUpdateVariableRegistryRequestBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this submit update variable registry request bad request response a status code equal to that given
func (o *SubmitUpdateVariableRegistryRequestBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *SubmitUpdateVariableRegistryRequestBadRequest) Error() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestBadRequest ", 400)
}

func (o *SubmitUpdateVariableRegistryRequestBadRequest) String() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestBadRequest ", 400)
}

func (o *SubmitUpdateVariableRegistryRequestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubmitUpdateVariableRegistryRequestUnauthorized creates a SubmitUpdateVariableRegistryRequestUnauthorized with default headers values
func NewSubmitUpdateVariableRegistryRequestUnauthorized() *SubmitUpdateVariableRegistryRequestUnauthorized {
	return &SubmitUpdateVariableRegistryRequestUnauthorized{}
}

/*
SubmitUpdateVariableRegistryRequestUnauthorized describes a response with status code 401, with default header values.

Client could not be authenticated.
*/
type SubmitUpdateVariableRegistryRequestUnauthorized struct {
}

// IsSuccess returns true when this submit update variable registry request unauthorized response has a 2xx status code
func (o *SubmitUpdateVariableRegistryRequestUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this submit update variable registry request unauthorized response has a 3xx status code
func (o *SubmitUpdateVariableRegistryRequestUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit update variable registry request unauthorized response has a 4xx status code
func (o *SubmitUpdateVariableRegistryRequestUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this submit update variable registry request unauthorized response has a 5xx status code
func (o *SubmitUpdateVariableRegistryRequestUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this submit update variable registry request unauthorized response a status code equal to that given
func (o *SubmitUpdateVariableRegistryRequestUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *SubmitUpdateVariableRegistryRequestUnauthorized) Error() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestUnauthorized ", 401)
}

func (o *SubmitUpdateVariableRegistryRequestUnauthorized) String() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestUnauthorized ", 401)
}

func (o *SubmitUpdateVariableRegistryRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubmitUpdateVariableRegistryRequestForbidden creates a SubmitUpdateVariableRegistryRequestForbidden with default headers values
func NewSubmitUpdateVariableRegistryRequestForbidden() *SubmitUpdateVariableRegistryRequestForbidden {
	return &SubmitUpdateVariableRegistryRequestForbidden{}
}

/*
SubmitUpdateVariableRegistryRequestForbidden describes a response with status code 403, with default header values.

Client is not authorized to make this request.
*/
type SubmitUpdateVariableRegistryRequestForbidden struct {
}

// IsSuccess returns true when this submit update variable registry request forbidden response has a 2xx status code
func (o *SubmitUpdateVariableRegistryRequestForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this submit update variable registry request forbidden response has a 3xx status code
func (o *SubmitUpdateVariableRegistryRequestForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit update variable registry request forbidden response has a 4xx status code
func (o *SubmitUpdateVariableRegistryRequestForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this submit update variable registry request forbidden response has a 5xx status code
func (o *SubmitUpdateVariableRegistryRequestForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this submit update variable registry request forbidden response a status code equal to that given
func (o *SubmitUpdateVariableRegistryRequestForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *SubmitUpdateVariableRegistryRequestForbidden) Error() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestForbidden ", 403)
}

func (o *SubmitUpdateVariableRegistryRequestForbidden) String() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestForbidden ", 403)
}

func (o *SubmitUpdateVariableRegistryRequestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubmitUpdateVariableRegistryRequestNotFound creates a SubmitUpdateVariableRegistryRequestNotFound with default headers values
func NewSubmitUpdateVariableRegistryRequestNotFound() *SubmitUpdateVariableRegistryRequestNotFound {
	return &SubmitUpdateVariableRegistryRequestNotFound{}
}

/*
SubmitUpdateVariableRegistryRequestNotFound describes a response with status code 404, with default header values.

The specified resource could not be found.
*/
type SubmitUpdateVariableRegistryRequestNotFound struct {
}

// IsSuccess returns true when this submit update variable registry request not found response has a 2xx status code
func (o *SubmitUpdateVariableRegistryRequestNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this submit update variable registry request not found response has a 3xx status code
func (o *SubmitUpdateVariableRegistryRequestNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit update variable registry request not found response has a 4xx status code
func (o *SubmitUpdateVariableRegistryRequestNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this submit update variable registry request not found response has a 5xx status code
func (o *SubmitUpdateVariableRegistryRequestNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this submit update variable registry request not found response a status code equal to that given
func (o *SubmitUpdateVariableRegistryRequestNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *SubmitUpdateVariableRegistryRequestNotFound) Error() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestNotFound ", 404)
}

func (o *SubmitUpdateVariableRegistryRequestNotFound) String() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestNotFound ", 404)
}

func (o *SubmitUpdateVariableRegistryRequestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubmitUpdateVariableRegistryRequestConflict creates a SubmitUpdateVariableRegistryRequestConflict with default headers values
func NewSubmitUpdateVariableRegistryRequestConflict() *SubmitUpdateVariableRegistryRequestConflict {
	return &SubmitUpdateVariableRegistryRequestConflict{}
}

/*
SubmitUpdateVariableRegistryRequestConflict describes a response with status code 409, with default header values.

The request was valid but NiFi was not in the appropriate state to process it. Retrying the same request later may be successful.
*/
type SubmitUpdateVariableRegistryRequestConflict struct {
}

// IsSuccess returns true when this submit update variable registry request conflict response has a 2xx status code
func (o *SubmitUpdateVariableRegistryRequestConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this submit update variable registry request conflict response has a 3xx status code
func (o *SubmitUpdateVariableRegistryRequestConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this submit update variable registry request conflict response has a 4xx status code
func (o *SubmitUpdateVariableRegistryRequestConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this submit update variable registry request conflict response has a 5xx status code
func (o *SubmitUpdateVariableRegistryRequestConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this submit update variable registry request conflict response a status code equal to that given
func (o *SubmitUpdateVariableRegistryRequestConflict) IsCode(code int) bool {
	return code == 409
}

func (o *SubmitUpdateVariableRegistryRequestConflict) Error() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestConflict ", 409)
}

func (o *SubmitUpdateVariableRegistryRequestConflict) String() string {
	return fmt.Sprintf("[POST /process-groups/{id}/variable-registry/update-requests][%d] submitUpdateVariableRegistryRequestConflict ", 409)
}

func (o *SubmitUpdateVariableRegistryRequestConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
