// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Bundle bundle
//
// swagger:model Bundle
type Bundle struct {

	// The artifact of the bundle
	Artifact string `json:"artifact,omitempty"`

	// The group of the bundle
	Group string `json:"group,omitempty"`

	// The version of the bundle
	Version string `json:"version,omitempty"`
}

// Validate validates this bundle
func (m *Bundle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bundle based on context it is used
func (m *Bundle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Bundle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Bundle) UnmarshalBinary(b []byte) error {
	var res Bundle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
