// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VersionedLabel versioned label
//
// swagger:model VersionedLabel
type VersionedLabel struct {

	// The user-supplied comments for the component
	Comments string `json:"comments,omitempty"`

	// component type
	// Enum: [CONNECTION PROCESSOR PROCESS_GROUP REMOTE_PROCESS_GROUP INPUT_PORT OUTPUT_PORT REMOTE_INPUT_PORT REMOTE_OUTPUT_PORT FUNNEL LABEL CONTROLLER_SERVICE]
	ComponentType string `json:"componentType,omitempty"`

	// The ID of the Process Group that this component belongs to
	GroupIdentifier string `json:"groupIdentifier,omitempty"`

	// The height of the label in pixels when at a 1:1 scale.
	Height float64 `json:"height,omitempty"`

	// The component's unique identifier
	Identifier string `json:"identifier,omitempty"`

	// The text that appears in the label.
	Label string `json:"label,omitempty"`

	// The component's name
	Name string `json:"name,omitempty"`

	// The component's position on the graph
	Position *Position `json:"position,omitempty"`

	// The styles for this label (font-size : 12px, background-color : #eee, etc).
	Style map[string]string `json:"style,omitempty"`

	// The width of the label in pixels when at a 1:1 scale.
	Width float64 `json:"width,omitempty"`
}

// Validate validates this versioned label
func (m *VersionedLabel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComponentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePosition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var versionedLabelTypeComponentTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CONNECTION","PROCESSOR","PROCESS_GROUP","REMOTE_PROCESS_GROUP","INPUT_PORT","OUTPUT_PORT","REMOTE_INPUT_PORT","REMOTE_OUTPUT_PORT","FUNNEL","LABEL","CONTROLLER_SERVICE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		versionedLabelTypeComponentTypePropEnum = append(versionedLabelTypeComponentTypePropEnum, v)
	}
}

const (

	// VersionedLabelComponentTypeCONNECTION captures enum value "CONNECTION"
	VersionedLabelComponentTypeCONNECTION string = "CONNECTION"

	// VersionedLabelComponentTypePROCESSOR captures enum value "PROCESSOR"
	VersionedLabelComponentTypePROCESSOR string = "PROCESSOR"

	// VersionedLabelComponentTypePROCESSGROUP captures enum value "PROCESS_GROUP"
	VersionedLabelComponentTypePROCESSGROUP string = "PROCESS_GROUP"

	// VersionedLabelComponentTypeREMOTEPROCESSGROUP captures enum value "REMOTE_PROCESS_GROUP"
	VersionedLabelComponentTypeREMOTEPROCESSGROUP string = "REMOTE_PROCESS_GROUP"

	// VersionedLabelComponentTypeINPUTPORT captures enum value "INPUT_PORT"
	VersionedLabelComponentTypeINPUTPORT string = "INPUT_PORT"

	// VersionedLabelComponentTypeOUTPUTPORT captures enum value "OUTPUT_PORT"
	VersionedLabelComponentTypeOUTPUTPORT string = "OUTPUT_PORT"

	// VersionedLabelComponentTypeREMOTEINPUTPORT captures enum value "REMOTE_INPUT_PORT"
	VersionedLabelComponentTypeREMOTEINPUTPORT string = "REMOTE_INPUT_PORT"

	// VersionedLabelComponentTypeREMOTEOUTPUTPORT captures enum value "REMOTE_OUTPUT_PORT"
	VersionedLabelComponentTypeREMOTEOUTPUTPORT string = "REMOTE_OUTPUT_PORT"

	// VersionedLabelComponentTypeFUNNEL captures enum value "FUNNEL"
	VersionedLabelComponentTypeFUNNEL string = "FUNNEL"

	// VersionedLabelComponentTypeLABEL captures enum value "LABEL"
	VersionedLabelComponentTypeLABEL string = "LABEL"

	// VersionedLabelComponentTypeCONTROLLERSERVICE captures enum value "CONTROLLER_SERVICE"
	VersionedLabelComponentTypeCONTROLLERSERVICE string = "CONTROLLER_SERVICE"
)

// prop value enum
func (m *VersionedLabel) validateComponentTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, versionedLabelTypeComponentTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *VersionedLabel) validateComponentType(formats strfmt.Registry) error {
	if swag.IsZero(m.ComponentType) { // not required
		return nil
	}

	// value enum
	if err := m.validateComponentTypeEnum("componentType", "body", m.ComponentType); err != nil {
		return err
	}

	return nil
}

func (m *VersionedLabel) validatePosition(formats strfmt.Registry) error {
	if swag.IsZero(m.Position) { // not required
		return nil
	}

	if m.Position != nil {
		if err := m.Position.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("position")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("position")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this versioned label based on the context it is used
func (m *VersionedLabel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePosition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionedLabel) contextValidatePosition(ctx context.Context, formats strfmt.Registry) error {

	if m.Position != nil {
		if err := m.Position.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("position")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("position")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionedLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionedLabel) UnmarshalBinary(b []byte) error {
	var res VersionedLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
