// Code generated by go-swagger; DO NOT EDIT.

package parameter_providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetParameterProviderReferencesParams creates a new GetParameterProviderReferencesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetParameterProviderReferencesParams() *GetParameterProviderReferencesParams {
	return &GetParameterProviderReferencesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetParameterProviderReferencesParamsWithTimeout creates a new GetParameterProviderReferencesParams object
// with the ability to set a timeout on a request.
func NewGetParameterProviderReferencesParamsWithTimeout(timeout time.Duration) *GetParameterProviderReferencesParams {
	return &GetParameterProviderReferencesParams{
		timeout: timeout,
	}
}

// NewGetParameterProviderReferencesParamsWithContext creates a new GetParameterProviderReferencesParams object
// with the ability to set a context for a request.
func NewGetParameterProviderReferencesParamsWithContext(ctx context.Context) *GetParameterProviderReferencesParams {
	return &GetParameterProviderReferencesParams{
		Context: ctx,
	}
}

// NewGetParameterProviderReferencesParamsWithHTTPClient creates a new GetParameterProviderReferencesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetParameterProviderReferencesParamsWithHTTPClient(client *http.Client) *GetParameterProviderReferencesParams {
	return &GetParameterProviderReferencesParams{
		HTTPClient: client,
	}
}

/*
GetParameterProviderReferencesParams contains all the parameters to send to the API endpoint

	for the get parameter provider references operation.

	Typically these are written to a http.Request.
*/
type GetParameterProviderReferencesParams struct {

	/* ID.

	   The parameter provider id.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get parameter provider references params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParameterProviderReferencesParams) WithDefaults() *GetParameterProviderReferencesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get parameter provider references params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParameterProviderReferencesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) WithTimeout(timeout time.Duration) *GetParameterProviderReferencesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) WithContext(ctx context.Context) *GetParameterProviderReferencesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) WithHTTPClient(client *http.Client) *GetParameterProviderReferencesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) WithID(id string) *GetParameterProviderReferencesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get parameter provider references params
func (o *GetParameterProviderReferencesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetParameterProviderReferencesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
