// Code generated by go-swagger; DO NOT EDIT.

package bundles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGlobalDeleteExtensionBundleParams creates a new GlobalDeleteExtensionBundleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGlobalDeleteExtensionBundleParams() *GlobalDeleteExtensionBundleParams {
	return &GlobalDeleteExtensionBundleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGlobalDeleteExtensionBundleParamsWithTimeout creates a new GlobalDeleteExtensionBundleParams object
// with the ability to set a timeout on a request.
func NewGlobalDeleteExtensionBundleParamsWithTimeout(timeout time.Duration) *GlobalDeleteExtensionBundleParams {
	return &GlobalDeleteExtensionBundleParams{
		timeout: timeout,
	}
}

// NewGlobalDeleteExtensionBundleParamsWithContext creates a new GlobalDeleteExtensionBundleParams object
// with the ability to set a context for a request.
func NewGlobalDeleteExtensionBundleParamsWithContext(ctx context.Context) *GlobalDeleteExtensionBundleParams {
	return &GlobalDeleteExtensionBundleParams{
		Context: ctx,
	}
}

// NewGlobalDeleteExtensionBundleParamsWithHTTPClient creates a new GlobalDeleteExtensionBundleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGlobalDeleteExtensionBundleParamsWithHTTPClient(client *http.Client) *GlobalDeleteExtensionBundleParams {
	return &GlobalDeleteExtensionBundleParams{
		HTTPClient: client,
	}
}

/*
GlobalDeleteExtensionBundleParams contains all the parameters to send to the API endpoint

	for the global delete extension bundle operation.

	Typically these are written to a http.Request.
*/
type GlobalDeleteExtensionBundleParams struct {

	/* BundleID.

	   The extension bundle identifier
	*/
	BundleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the global delete extension bundle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GlobalDeleteExtensionBundleParams) WithDefaults() *GlobalDeleteExtensionBundleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the global delete extension bundle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GlobalDeleteExtensionBundleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) WithTimeout(timeout time.Duration) *GlobalDeleteExtensionBundleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) WithContext(ctx context.Context) *GlobalDeleteExtensionBundleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) WithHTTPClient(client *http.Client) *GlobalDeleteExtensionBundleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBundleID adds the bundleID to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) WithBundleID(bundleID string) *GlobalDeleteExtensionBundleParams {
	o.SetBundleID(bundleID)
	return o
}

// SetBundleID adds the bundleId to the global delete extension bundle params
func (o *GlobalDeleteExtensionBundleParams) SetBundleID(bundleID string) {
	o.BundleID = bundleID
}

// WriteToRequest writes these params to a swagger request
func (o *GlobalDeleteExtensionBundleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bundleId
	if err := r.SetPathParam("bundleId", o.BundleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
