// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccessPolicyForResourceParams creates a new GetAccessPolicyForResourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccessPolicyForResourceParams() *GetAccessPolicyForResourceParams {
	return &GetAccessPolicyForResourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccessPolicyForResourceParamsWithTimeout creates a new GetAccessPolicyForResourceParams object
// with the ability to set a timeout on a request.
func NewGetAccessPolicyForResourceParamsWithTimeout(timeout time.Duration) *GetAccessPolicyForResourceParams {
	return &GetAccessPolicyForResourceParams{
		timeout: timeout,
	}
}

// NewGetAccessPolicyForResourceParamsWithContext creates a new GetAccessPolicyForResourceParams object
// with the ability to set a context for a request.
func NewGetAccessPolicyForResourceParamsWithContext(ctx context.Context) *GetAccessPolicyForResourceParams {
	return &GetAccessPolicyForResourceParams{
		Context: ctx,
	}
}

// NewGetAccessPolicyForResourceParamsWithHTTPClient creates a new GetAccessPolicyForResourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccessPolicyForResourceParamsWithHTTPClient(client *http.Client) *GetAccessPolicyForResourceParams {
	return &GetAccessPolicyForResourceParams{
		HTTPClient: client,
	}
}

/*
GetAccessPolicyForResourceParams contains all the parameters to send to the API endpoint

	for the get access policy for resource operation.

	Typically these are written to a http.Request.
*/
type GetAccessPolicyForResourceParams struct {

	/* Action.

	   The request action.
	*/
	Action string

	/* Resource.

	   The resource of the policy.
	*/
	Resource string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get access policy for resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccessPolicyForResourceParams) WithDefaults() *GetAccessPolicyForResourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get access policy for resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccessPolicyForResourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) WithTimeout(timeout time.Duration) *GetAccessPolicyForResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) WithContext(ctx context.Context) *GetAccessPolicyForResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) WithHTTPClient(client *http.Client) *GetAccessPolicyForResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAction adds the action to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) WithAction(action string) *GetAccessPolicyForResourceParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) SetAction(action string) {
	o.Action = action
}

// WithResource adds the resource to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) WithResource(resource string) *GetAccessPolicyForResourceParams {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the get access policy for resource params
func (o *GetAccessPolicyForResourceParams) SetResource(resource string) {
	o.Resource = resource
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccessPolicyForResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param action
	if err := r.SetPathParam("action", o.Action); err != nil {
		return err
	}

	// path param resource
	if err := r.SetPathParam("resource", o.Resource); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
