// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skycubed/nifi-go/pkg/registry/models"
)

// GetTagsReader is a Reader for the GetTags structure.
type GetTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTagsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetTagsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetTagsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetTagsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetTagsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTagsOK creates a GetTagsOK with default headers values
func NewGetTagsOK() *GetTagsOK {
	return &GetTagsOK{}
}

/* GetTagsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTagsOK struct {
	Payload []*models.TagCount
}

func (o *GetTagsOK) Error() string {
	return fmt.Sprintf("[GET /extensions/tags][%d] getTagsOK  %+v", 200, o.Payload)
}
func (o *GetTagsOK) GetPayload() []*models.TagCount {
	return o.Payload
}

func (o *GetTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTagsBadRequest creates a GetTagsBadRequest with default headers values
func NewGetTagsBadRequest() *GetTagsBadRequest {
	return &GetTagsBadRequest{}
}

/* GetTagsBadRequest describes a response with status code 400, with default header values.

NiFi Registry was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type GetTagsBadRequest struct {
}

func (o *GetTagsBadRequest) Error() string {
	return fmt.Sprintf("[GET /extensions/tags][%d] getTagsBadRequest ", 400)
}

func (o *GetTagsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTagsUnauthorized creates a GetTagsUnauthorized with default headers values
func NewGetTagsUnauthorized() *GetTagsUnauthorized {
	return &GetTagsUnauthorized{}
}

/* GetTagsUnauthorized describes a response with status code 401, with default header values.

Client could not be authenticated.
*/
type GetTagsUnauthorized struct {
}

func (o *GetTagsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /extensions/tags][%d] getTagsUnauthorized ", 401)
}

func (o *GetTagsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTagsForbidden creates a GetTagsForbidden with default headers values
func NewGetTagsForbidden() *GetTagsForbidden {
	return &GetTagsForbidden{}
}

/* GetTagsForbidden describes a response with status code 403, with default header values.

Client is not authorized to make this request.
*/
type GetTagsForbidden struct {
}

func (o *GetTagsForbidden) Error() string {
	return fmt.Sprintf("[GET /extensions/tags][%d] getTagsForbidden ", 403)
}

func (o *GetTagsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTagsNotFound creates a GetTagsNotFound with default headers values
func NewGetTagsNotFound() *GetTagsNotFound {
	return &GetTagsNotFound{}
}

/* GetTagsNotFound describes a response with status code 404, with default header values.

The specified resource could not be found.
*/
type GetTagsNotFound struct {
}

func (o *GetTagsNotFound) Error() string {
	return fmt.Sprintf("[GET /extensions/tags][%d] getTagsNotFound ", 404)
}

func (o *GetTagsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTagsConflict creates a GetTagsConflict with default headers values
func NewGetTagsConflict() *GetTagsConflict {
	return &GetTagsConflict{}
}

/* GetTagsConflict describes a response with status code 409, with default header values.

NiFi Registry was unable to complete the request because it assumes a server state that is not valid.
*/
type GetTagsConflict struct {
}

func (o *GetTagsConflict) Error() string {
	return fmt.Sprintf("[GET /extensions/tags][%d] getTagsConflict ", 409)
}

func (o *GetTagsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
