// Code generated by go-swagger; DO NOT EDIT.

package bucket_flows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFlowVersionsParams creates a new GetFlowVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFlowVersionsParams() *GetFlowVersionsParams {
	return &GetFlowVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFlowVersionsParamsWithTimeout creates a new GetFlowVersionsParams object
// with the ability to set a timeout on a request.
func NewGetFlowVersionsParamsWithTimeout(timeout time.Duration) *GetFlowVersionsParams {
	return &GetFlowVersionsParams{
		timeout: timeout,
	}
}

// NewGetFlowVersionsParamsWithContext creates a new GetFlowVersionsParams object
// with the ability to set a context for a request.
func NewGetFlowVersionsParamsWithContext(ctx context.Context) *GetFlowVersionsParams {
	return &GetFlowVersionsParams{
		Context: ctx,
	}
}

// NewGetFlowVersionsParamsWithHTTPClient creates a new GetFlowVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFlowVersionsParamsWithHTTPClient(client *http.Client) *GetFlowVersionsParams {
	return &GetFlowVersionsParams{
		HTTPClient: client,
	}
}

/* GetFlowVersionsParams contains all the parameters to send to the API endpoint
   for the get flow versions operation.

   Typically these are written to a http.Request.
*/
type GetFlowVersionsParams struct {

	/* BucketID.

	   The bucket identifier
	*/
	BucketID string

	/* FlowID.

	   The flow identifier
	*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get flow versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFlowVersionsParams) WithDefaults() *GetFlowVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get flow versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFlowVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get flow versions params
func (o *GetFlowVersionsParams) WithTimeout(timeout time.Duration) *GetFlowVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get flow versions params
func (o *GetFlowVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get flow versions params
func (o *GetFlowVersionsParams) WithContext(ctx context.Context) *GetFlowVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get flow versions params
func (o *GetFlowVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get flow versions params
func (o *GetFlowVersionsParams) WithHTTPClient(client *http.Client) *GetFlowVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get flow versions params
func (o *GetFlowVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketID adds the bucketID to the get flow versions params
func (o *GetFlowVersionsParams) WithBucketID(bucketID string) *GetFlowVersionsParams {
	o.SetBucketID(bucketID)
	return o
}

// SetBucketID adds the bucketId to the get flow versions params
func (o *GetFlowVersionsParams) SetBucketID(bucketID string) {
	o.BucketID = bucketID
}

// WithFlowID adds the flowID to the get flow versions params
func (o *GetFlowVersionsParams) WithFlowID(flowID string) *GetFlowVersionsParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the get flow versions params
func (o *GetFlowVersionsParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFlowVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucketId
	if err := r.SetPathParam("bucketId", o.BucketID); err != nil {
		return err
	}

	// path param flowId
	if err := r.SetPathParam("flowId", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
