// Code generated by go-swagger; DO NOT EDIT.

package versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportFlowVersionParams creates a new ExportFlowVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportFlowVersionParams() *ExportFlowVersionParams {
	return &ExportFlowVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportFlowVersionParamsWithTimeout creates a new ExportFlowVersionParams object
// with the ability to set a timeout on a request.
func NewExportFlowVersionParamsWithTimeout(timeout time.Duration) *ExportFlowVersionParams {
	return &ExportFlowVersionParams{
		timeout: timeout,
	}
}

// NewExportFlowVersionParamsWithContext creates a new ExportFlowVersionParams object
// with the ability to set a context for a request.
func NewExportFlowVersionParamsWithContext(ctx context.Context) *ExportFlowVersionParams {
	return &ExportFlowVersionParams{
		Context: ctx,
	}
}

// NewExportFlowVersionParamsWithHTTPClient creates a new ExportFlowVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportFlowVersionParamsWithHTTPClient(client *http.Client) *ExportFlowVersionParams {
	return &ExportFlowVersionParams{
		HTTPClient: client,
	}
}

/*
ExportFlowVersionParams contains all the parameters to send to the API endpoint

	for the export flow version operation.

	Typically these are written to a http.Request.
*/
type ExportFlowVersionParams struct {

	/* ID.

	   The process group id.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export flow version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportFlowVersionParams) WithDefaults() *ExportFlowVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export flow version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportFlowVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export flow version params
func (o *ExportFlowVersionParams) WithTimeout(timeout time.Duration) *ExportFlowVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export flow version params
func (o *ExportFlowVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export flow version params
func (o *ExportFlowVersionParams) WithContext(ctx context.Context) *ExportFlowVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export flow version params
func (o *ExportFlowVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export flow version params
func (o *ExportFlowVersionParams) WithHTTPClient(client *http.Client) *ExportFlowVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export flow version params
func (o *ExportFlowVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the export flow version params
func (o *ExportFlowVersionParams) WithID(id string) *ExportFlowVersionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the export flow version params
func (o *ExportFlowVersionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExportFlowVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
