// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserGroupsParams creates a new GetUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserGroupsParams() *GetUserGroupsParams {
	return &GetUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserGroupsParamsWithTimeout creates a new GetUserGroupsParams object
// with the ability to set a timeout on a request.
func NewGetUserGroupsParamsWithTimeout(timeout time.Duration) *GetUserGroupsParams {
	return &GetUserGroupsParams{
		timeout: timeout,
	}
}

// NewGetUserGroupsParamsWithContext creates a new GetUserGroupsParams object
// with the ability to set a context for a request.
func NewGetUserGroupsParamsWithContext(ctx context.Context) *GetUserGroupsParams {
	return &GetUserGroupsParams{
		Context: ctx,
	}
}

// NewGetUserGroupsParamsWithHTTPClient creates a new GetUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserGroupsParamsWithHTTPClient(client *http.Client) *GetUserGroupsParams {
	return &GetUserGroupsParams{
		HTTPClient: client,
	}
}

/* GetUserGroupsParams contains all the parameters to send to the API endpoint
   for the get user groups operation.

   Typically these are written to a http.Request.
*/
type GetUserGroupsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserGroupsParams) WithDefaults() *GetUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user groups params
func (o *GetUserGroupsParams) WithTimeout(timeout time.Duration) *GetUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user groups params
func (o *GetUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user groups params
func (o *GetUserGroupsParams) WithContext(ctx context.Context) *GetUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user groups params
func (o *GetUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user groups params
func (o *GetUserGroupsParams) WithHTTPClient(client *http.Client) *GetUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user groups params
func (o *GetUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
